name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  latest:
    runs-on: ubuntu-latest
    container: thinca/vim:latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          vim --version
          make setup
      - name: lint
        run: make lint
      - name: test
        run: make test
